### ISSUE TITLE
Example only wraps the first text found

### ISSUE THREAD

**Issue by BigBlueHat** [tilgovi/dom-seek#5]
I put the example into RequireBin.com, added some [lipsum](http://lipsum.org), and switch `span` to `mark` ('cause I'm lazy and didn't want to write any CSS), and got this:
http://requirebin.com/?gist=BigBlueHat/05e6de117697faf4d414

Only the first `ipsum` is highlighted.

**Comment by tilgovi** [comment]
It's only an example. If you'd like to provide a better one, please send a PR!

:shipit:
